version: "3.6"
services:
  web:
    tty: true
    stdin_open: true
    build: .
    container_name: rails-react-graphql-web
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-react-graphql
      - web-gems:/home/rails-react-graphql
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    command: >
      sh -c '
        bundle check || bundle install &&
        rm -f tmp/pids/server.pid &&
        rails s -b 0.0.0.0'
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3-alpine
    container_name: rails-react-graphql-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
volumes:
  web-gems:
  postgres-data:
